import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        'foreground': 'rgb(var(--foreground-rgb))',
        'background-start': 'rgb(var(--background-start-rgb))',
        'background-end': 'rgb(var(--background-end-rgb))',
        'brand-default': 'var(--brand-default)',
        'brand-fainter': 'var(--brand-fainter)',
        'brand-faint': 'var(--brand-faint)',
        'brand-subtle': 'var(--brand-subtle)',
        'brand-muted': 'var(--brand-muted)',
        'brand-dark': 'var(--brand-dark)',
        'brand-darker': 'var(--brand-darker)',
        'secondary-accent': 'var(--secondary-accent)',
        'secondary-accent2x': 'var(--secondary-accent2x)',
        'secondary-dark': 'var(--secondary-dark)',
        'secondary-darker': 'var(--secondary-darker)',
        'secondary-darkest': 'var(--secondary-darkest)',
        'secondary-default': 'var(--secondary-default)',
        'secondary-faint': 'var(--secondary-faint)',
        'secondary-fainter': 'var(--secondary-fainter)',
        'gray-100': 'var(--gray-100)',
        'gray-200': 'var(--gray-200)',
        'gray-300': 'var(--gray-300)',
        'gray-400': 'var(--gray-400)',
        'gray-50': 'var(--gray-50)',
        'gray-500': 'var(--gray-500)',
        'gray-600': 'var(--gray-600)',
        'gray-700': 'var(--gray-700)',
        'gray-800': 'var(--gray-800)',
        'gray-900': 'var(--gray-900)',
        'gray-950': 'var(--gray-950)',
        'black': 'var(--black)',
        'white': 'var(--white)',
        'accent-yellow-light': 'var(--accent-yellow-light)',
        'accent-yellow-dark': 'var(--accent-yellow-dark)',
        'accent-skyblue-light': 'var(--accent-skyblue-light)',
        'accent-skyblue-dark': 'var(--accent-skyblue-dark)',
        'accent-green': 'var(--accent-green)',
        'accent-red': 'var(--accent-red)',
        'accent-darkgreen-dark': 'var(--accent-darkgreen-dark)',
        'accent-darkgreen-light': 'var(--accent-darkgreen-light)',
        'accent-purple-dark': 'var(--accent-purple-dark)',
        'accent-purple-light': 'var(--accent-purple-light)',
        'accent-pink-dark': 'var(--accent-pink-dark)',
        'accent-pink-light': 'var(--accent-pink-light)',
        'accent-maroon-dark': 'var(--accent-maroon-dark)',
        'accent-maroon-light': 'var(--accent-maroon-light)',
        'dark-accent-skyblue-dark': 'var(--dark-accent-skyblue-dark)',
        'dark-accent-skyblue-light': 'var(--dark-accent-skyblue-light)',
        'dark-accent-maroon-dark': 'var(--dark-accent-maroon-dark)',
        'dark-accent-maroon-light': 'var(--dark-accent-maroon-light)',
        'dark-accent-green-dark': 'var(--dark-accent-green-dark)',
        'dark-accent-green-light': 'var(--dark-accent-green-light)',
        'dark-accent-yellow-dark': 'var(--dark-accent-yellow-dark)',
        'dark-accent-yellow-light': 'var(--dark-accent-yellow-light)',
        'dark-accent-purple-dark': 'var(--dark-accent-purple-dark)',
        'dark-accent-purple-light': 'var(--dark-accent-purple-light)',
        'dark-accent-pink-dark': 'var(--dark-accent-pink-dark)',
        'dark-accent-pink-light': 'var(--dark-accent-pink-light)',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: ["light"],
  },

};
export default config;
